package com.fly.dao.teaching;

import com.fly.pojo.teaching.Students;

import java.util.List;

/**
 * @author fly
 */
public interface StudentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_students
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     *
     */
    /**
     * 删除学生
     * @param id 删除学生ID
     * @return 受影响的行数
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_students
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    /**
     * 插入学生
     * @param record  学生对象
     * @return 数据修改行数
     */
    int insert(Students record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_students
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    /**
     * 采用动态SQL插入学生
     * @param record 学生对象
     * @return 数据邮箱行数
     */
    int insertSelective(Students record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_students
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    /**
     * 根据学生ID查找学生
     * @param id 学生ID
     * @return 学生对象
     */
    Students selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_students
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    int updateByPrimaryKeySelective(Students record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_students
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    int updateByPrimaryKey(Students record);

    /**
     * 分页查询学生,这里采用了pageHelper插件,所以不需要传入page/limit等参数
     * @return 每一页的学生对象组成的集合
     */

    List<Students> selectStudentAll();

}