package com.fly.pojo.teaching;

import java.util.Date;

public class Students {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.Id
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.Name
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.Age
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.Sex
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.Phone
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.StuStatus
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String stustatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.PerState
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String perstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.MsgSource
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String msgsource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.SourceUrl
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String sourceurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.SourceKeyWord
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String sourcekeyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.Address
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.NetPusherId
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String netpusherid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.AskerId
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private Integer askerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.QQ
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.WeiXin
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String weixin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.Content
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.CreateTime
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.LearnForward
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String learnforward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.IsValid
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String isvalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.Record
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String record;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.IsReturnVist
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String isreturnvist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.FirstVisitTime
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private Date firstvisittime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.IsHome
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String ishome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.HomeTime
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private Date hometime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.LostValid
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String lostvalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.IsPay
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String ispay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.PayTime
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private Date paytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.Money
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.IsReturnMoney
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String isreturnmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.IsInClass
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String isinclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.InClassTime
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private Date inclasstime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.InClassContent
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String inclasscontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.AskerContent
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String askercontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.IsDel
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.FromPart
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String frompart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.StuConcern
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String stuconcern;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.IsBaoBei
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String isbaobei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.teacherID
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String teacherid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.classID
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String classid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.CreateUser
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.ReturnMoneyReason
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private String returnmoneyreason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.PreMoney
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private Double premoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_students.PreMoneyTime
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    private Date premoneytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.Id
     *
     * @return the value of spring_students.Id
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.Id
     *
     * @param id the value for spring_students.Id
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.Name
     *
     * @return the value of spring_students.Name
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.Name
     *
     * @param name the value for spring_students.Name
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.Age
     *
     * @return the value of spring_students.Age
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.Age
     *
     * @param age the value for spring_students.Age
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.Sex
     *
     * @return the value of spring_students.Sex
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.Sex
     *
     * @param sex the value for spring_students.Sex
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.Phone
     *
     * @return the value of spring_students.Phone
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.Phone
     *
     * @param phone the value for spring_students.Phone
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.StuStatus
     *
     * @return the value of spring_students.StuStatus
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getStustatus() {
        return stustatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.StuStatus
     *
     * @param stustatus the value for spring_students.StuStatus
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setStustatus(String stustatus) {
        this.stustatus = stustatus == null ? null : stustatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.PerState
     *
     * @return the value of spring_students.PerState
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getPerstate() {
        return perstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.PerState
     *
     * @param perstate the value for spring_students.PerState
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setPerstate(String perstate) {
        this.perstate = perstate == null ? null : perstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.MsgSource
     *
     * @return the value of spring_students.MsgSource
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getMsgsource() {
        return msgsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.MsgSource
     *
     * @param msgsource the value for spring_students.MsgSource
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setMsgsource(String msgsource) {
        this.msgsource = msgsource == null ? null : msgsource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.SourceUrl
     *
     * @return the value of spring_students.SourceUrl
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getSourceurl() {
        return sourceurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.SourceUrl
     *
     * @param sourceurl the value for spring_students.SourceUrl
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setSourceurl(String sourceurl) {
        this.sourceurl = sourceurl == null ? null : sourceurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.SourceKeyWord
     *
     * @return the value of spring_students.SourceKeyWord
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getSourcekeyword() {
        return sourcekeyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.SourceKeyWord
     *
     * @param sourcekeyword the value for spring_students.SourceKeyWord
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setSourcekeyword(String sourcekeyword) {
        this.sourcekeyword = sourcekeyword == null ? null : sourcekeyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.Address
     *
     * @return the value of spring_students.Address
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.Address
     *
     * @param address the value for spring_students.Address
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.NetPusherId
     *
     * @return the value of spring_students.NetPusherId
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getNetpusherid() {
        return netpusherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.NetPusherId
     *
     * @param netpusherid the value for spring_students.NetPusherId
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setNetpusherid(String netpusherid) {
        this.netpusherid = netpusherid == null ? null : netpusherid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.AskerId
     *
     * @return the value of spring_students.AskerId
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public Integer getAskerid() {
        return askerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.AskerId
     *
     * @param askerid the value for spring_students.AskerId
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setAskerid(Integer askerid) {
        this.askerid = askerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.QQ
     *
     * @return the value of spring_students.QQ
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.QQ
     *
     * @param qq the value for spring_students.QQ
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.WeiXin
     *
     * @return the value of spring_students.WeiXin
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.WeiXin
     *
     * @param weixin the value for spring_students.WeiXin
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin == null ? null : weixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.Content
     *
     * @return the value of spring_students.Content
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.Content
     *
     * @param content the value for spring_students.Content
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.CreateTime
     *
     * @return the value of spring_students.CreateTime
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.CreateTime
     *
     * @param createtime the value for spring_students.CreateTime
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.LearnForward
     *
     * @return the value of spring_students.LearnForward
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getLearnforward() {
        return learnforward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.LearnForward
     *
     * @param learnforward the value for spring_students.LearnForward
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setLearnforward(String learnforward) {
        this.learnforward = learnforward == null ? null : learnforward.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.IsValid
     *
     * @return the value of spring_students.IsValid
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.IsValid
     *
     * @param isvalid the value for spring_students.IsValid
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setIsvalid(String isvalid) {
        this.isvalid = isvalid == null ? null : isvalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.Record
     *
     * @return the value of spring_students.Record
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getRecord() {
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.Record
     *
     * @param record the value for spring_students.Record
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setRecord(String record) {
        this.record = record == null ? null : record.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.IsReturnVist
     *
     * @return the value of spring_students.IsReturnVist
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getIsreturnvist() {
        return isreturnvist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.IsReturnVist
     *
     * @param isreturnvist the value for spring_students.IsReturnVist
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setIsreturnvist(String isreturnvist) {
        this.isreturnvist = isreturnvist == null ? null : isreturnvist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.FirstVisitTime
     *
     * @return the value of spring_students.FirstVisitTime
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public Date getFirstvisittime() {
        return firstvisittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.FirstVisitTime
     *
     * @param firstvisittime the value for spring_students.FirstVisitTime
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setFirstvisittime(Date firstvisittime) {
        this.firstvisittime = firstvisittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.IsHome
     *
     * @return the value of spring_students.IsHome
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getIshome() {
        return ishome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.IsHome
     *
     * @param ishome the value for spring_students.IsHome
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setIshome(String ishome) {
        this.ishome = ishome == null ? null : ishome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.HomeTime
     *
     * @return the value of spring_students.HomeTime
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public Date getHometime() {
        return hometime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.HomeTime
     *
     * @param hometime the value for spring_students.HomeTime
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setHometime(Date hometime) {
        this.hometime = hometime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.LostValid
     *
     * @return the value of spring_students.LostValid
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getLostvalid() {
        return lostvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.LostValid
     *
     * @param lostvalid the value for spring_students.LostValid
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setLostvalid(String lostvalid) {
        this.lostvalid = lostvalid == null ? null : lostvalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.IsPay
     *
     * @return the value of spring_students.IsPay
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getIspay() {
        return ispay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.IsPay
     *
     * @param ispay the value for spring_students.IsPay
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setIspay(String ispay) {
        this.ispay = ispay == null ? null : ispay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.PayTime
     *
     * @return the value of spring_students.PayTime
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.PayTime
     *
     * @param paytime the value for spring_students.PayTime
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.Money
     *
     * @return the value of spring_students.Money
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.Money
     *
     * @param money the value for spring_students.Money
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.IsReturnMoney
     *
     * @return the value of spring_students.IsReturnMoney
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getIsreturnmoney() {
        return isreturnmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.IsReturnMoney
     *
     * @param isreturnmoney the value for spring_students.IsReturnMoney
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setIsreturnmoney(String isreturnmoney) {
        this.isreturnmoney = isreturnmoney == null ? null : isreturnmoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.IsInClass
     *
     * @return the value of spring_students.IsInClass
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getIsinclass() {
        return isinclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.IsInClass
     *
     * @param isinclass the value for spring_students.IsInClass
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setIsinclass(String isinclass) {
        this.isinclass = isinclass == null ? null : isinclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.InClassTime
     *
     * @return the value of spring_students.InClassTime
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public Date getInclasstime() {
        return inclasstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.InClassTime
     *
     * @param inclasstime the value for spring_students.InClassTime
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setInclasstime(Date inclasstime) {
        this.inclasstime = inclasstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.InClassContent
     *
     * @return the value of spring_students.InClassContent
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getInclasscontent() {
        return inclasscontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.InClassContent
     *
     * @param inclasscontent the value for spring_students.InClassContent
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setInclasscontent(String inclasscontent) {
        this.inclasscontent = inclasscontent == null ? null : inclasscontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.AskerContent
     *
     * @return the value of spring_students.AskerContent
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getAskercontent() {
        return askercontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.AskerContent
     *
     * @param askercontent the value for spring_students.AskerContent
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setAskercontent(String askercontent) {
        this.askercontent = askercontent == null ? null : askercontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.IsDel
     *
     * @return the value of spring_students.IsDel
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.IsDel
     *
     * @param isdel the value for spring_students.IsDel
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setIsdel(String isdel) {
        this.isdel = isdel == null ? null : isdel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.FromPart
     *
     * @return the value of spring_students.FromPart
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getFrompart() {
        return frompart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.FromPart
     *
     * @param frompart the value for spring_students.FromPart
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setFrompart(String frompart) {
        this.frompart = frompart == null ? null : frompart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.StuConcern
     *
     * @return the value of spring_students.StuConcern
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getStuconcern() {
        return stuconcern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.StuConcern
     *
     * @param stuconcern the value for spring_students.StuConcern
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setStuconcern(String stuconcern) {
        this.stuconcern = stuconcern == null ? null : stuconcern.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.IsBaoBei
     *
     * @return the value of spring_students.IsBaoBei
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getIsbaobei() {
        return isbaobei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.IsBaoBei
     *
     * @param isbaobei the value for spring_students.IsBaoBei
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setIsbaobei(String isbaobei) {
        this.isbaobei = isbaobei == null ? null : isbaobei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.teacherID
     *
     * @return the value of spring_students.teacherID
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.teacherID
     *
     * @param teacherid the value for spring_students.teacherID
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setTeacherid(String teacherid) {
        this.teacherid = teacherid == null ? null : teacherid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.classID
     *
     * @return the value of spring_students.classID
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.classID
     *
     * @param classid the value for spring_students.classID
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setClassid(String classid) {
        this.classid = classid == null ? null : classid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.CreateUser
     *
     * @return the value of spring_students.CreateUser
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.CreateUser
     *
     * @param createuser the value for spring_students.CreateUser
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.ReturnMoneyReason
     *
     * @return the value of spring_students.ReturnMoneyReason
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public String getReturnmoneyreason() {
        return returnmoneyreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.ReturnMoneyReason
     *
     * @param returnmoneyreason the value for spring_students.ReturnMoneyReason
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setReturnmoneyreason(String returnmoneyreason) {
        this.returnmoneyreason = returnmoneyreason == null ? null : returnmoneyreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.PreMoney
     *
     * @return the value of spring_students.PreMoney
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public Double getPremoney() {
        return premoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.PreMoney
     *
     * @param premoney the value for spring_students.PreMoney
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setPremoney(Double premoney) {
        this.premoney = premoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_students.PreMoneyTime
     *
     * @return the value of spring_students.PreMoneyTime
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public Date getPremoneytime() {
        return premoneytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_students.PreMoneyTime
     *
     * @param premoneytime the value for spring_students.PreMoneyTime
     *
     * @mbg.generated Wed Jun 13 10:54:46 CST 2018
     */
    public void setPremoneytime(Date premoneytime) {
        this.premoneytime = premoneytime;
    }

    @Override
    public String toString() {
        return "Students{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", age=" + age +
                ", sex='" + sex + '\'' +
                ", phone='" + phone + '\'' +
                ", stustatus='" + stustatus + '\'' +
                ", perstate='" + perstate + '\'' +
                ", msgsource='" + msgsource + '\'' +
                ", sourceurl='" + sourceurl + '\'' +
                ", sourcekeyword='" + sourcekeyword + '\'' +
                ", address='" + address + '\'' +
                ", netpusherid='" + netpusherid + '\'' +
                ", askerid=" + askerid +
                ", qq='" + qq + '\'' +
                ", weixin='" + weixin + '\'' +
                ", content='" + content + '\'' +
                ", createtime=" + createtime +
                ", learnforward='" + learnforward + '\'' +
                ", isvalid='" + isvalid + '\'' +
                ", record='" + record + '\'' +
                ", isreturnvist='" + isreturnvist + '\'' +
                ", firstvisittime=" + firstvisittime +
                ", ishome='" + ishome + '\'' +
                ", hometime=" + hometime +
                ", lostvalid='" + lostvalid + '\'' +
                ", ispay='" + ispay + '\'' +
                ", paytime=" + paytime +
                ", money=" + money +
                ", isreturnmoney='" + isreturnmoney + '\'' +
                ", isinclass='" + isinclass + '\'' +
                ", inclasstime=" + inclasstime +
                ", inclasscontent='" + inclasscontent + '\'' +
                ", askercontent='" + askercontent + '\'' +
                ", isdel='" + isdel + '\'' +
                ", frompart='" + frompart + '\'' +
                ", stuconcern='" + stuconcern + '\'' +
                ", isbaobei='" + isbaobei + '\'' +
                ", teacherid='" + teacherid + '\'' +
                ", classid='" + classid + '\'' +
                ", createuser='" + createuser + '\'' +
                ", returnmoneyreason='" + returnmoneyreason + '\'' +
                ", premoney=" + premoney +
                ", premoneytime=" + premoneytime +
                '}';
    }
}